import sqlite3
import pandas as pd
from config import DB_PATH

def ingest_data():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    print(f"📡 System Configuration Loaded | DB: {DB_PATH}")

    # 1. FORCE RESET: Drop the old schema to apply the new User-Centric architecture
    print("⚠️  Resetting schema for Phase 2 hardening...")
    cursor.execute("DROP TABLE IF EXISTS ledger")

    # 2. Table Creation with 'user_id' for Spatiotemporal Tracking
    # This architecture allows us to link transactions to specific users
    cursor.execute("""
        CREATE TABLE ledger (
            txn_id TEXT PRIMARY KEY, 
            user_id TEXT NOT NULL,
            user_tier TEXT NOT NULL,
            amount_inr REAL NOT NULL CHECK(amount_inr > 0),
            city TEXT DEFAULT 'UNKNOWN',
            status TEXT,
            timestamp DATETIME NOT NULL
        )
    """)
    
    # 3. Performance Indexing
    # Essential for Phase 3 scaling to 1M+ transactions
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_timestamp ON ledger(timestamp);")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_user ON ledger(user_id);")

    # 4. Load the CSV generated by day2_generator.py
    try:
        df = pd.read_csv('day2_transactions.csv')
        
        # 5. Data Ingestion
        # We use 'append' because we manually cleared the table above
        df.to_sql('ledger', conn, if_exists='append', index=False)
        
        conn.commit()
        print(f"✅ Success: Data hardened with User-Centric indexing in Central Vault.")
    
    except FileNotFoundError:
        print("❌ Error: 'day2_transactions.csv' not found. Run the generator first.")
    except Exception as e:
        print(f"❌ Ingestion failed: {e}")
    finally:
        conn.close()

if __name__ == "__main__":
    ingest_data()